# Generated by Django 2.0.7 on 2019-05-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('objective', models.TextField()),
                ('result', models.TextField()),
                ('year', models.PositiveSmallIntegerField(max_length=4)),
            ],
        ),
    ]
