# Generated by Django 2.0.7 on 2019-10-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_auto_20190514_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='link',
            field=models.CharField(default='laymean.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='paper',
            name='objective',
            field=models.TextField(default='No abstract available'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='result',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
